spring:
  application:
    name: weatherServiceAdapter
server:
    port: 8080
    host: 'localhost'
camel:
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /*
weather-service:
  api:
    path:
      adapterServiceA: '/api/serviceA'
      serviceB: 'https://hostForServiceB.ru/api/serviceB'
      weatherServiceAPI: 'https://www.gismeteo.ru/api'
      mockWeatherServiceAPI: 'mock://https:www.gismeteo.ru/api'
      serviceBhost: 'localhost'
      serviceBport: '8090'
